# http://164.90.165.141:8080

### get unfiltered recipes
GET http://localhost:8080/api/recipes

### get filtered recipes
GET http://localhost:8080/api/recipes?servings=2&time=12&difficulty=medium&media=game&taste=spicy&vegetarian=false

### get specific recipe
GET http://164.90.165.141:8080/api/recipe/cl3ct18u5125501yeljjyir04

### get search name Random
GET http://localhost:8080/api/recipes?name=st\ ts


### create new recipe
POST http://localhost:8080/api/recipe
Content-Type: application/json

{
  "name": "test tsar",
  "description": "test long text but longer",
  "servings": 2,
  "time": 10,
  "reference": "Random movie",
  "difficulty": "hard",
  "media": "movie",
  "taste": "sour",
  "vegetarian": false,
  "ingredients": [
    {
      "name": "trava zelena",
      "amount": 10,
      "unit": "pieces"
    },
    {
      "name": "voda",
      "amount": 1000,
      "unit": "ml"
    }
  ]
}

### delete recipe
DELETE http://localhost:8080/api/recipe/cl3ct18u5125501yeljjyir04
