# http://164.90.165.141:8080

### get unfiltered recipes
GET http://localhost:8080/api/recipes

### get filtered recipes
GET http://localhost:8080/api/recipes?servings=2&time=201&difficulty=HARD&media=MOVIE&taste=SOUR&vegetarian=false

### get specific recipe
GET http://localhost:8080/api/recipe/cl3c1f1h30000z6ezyrvv9btj

### get search name Random
GET http://localhost:8080/api/recipes?name=trsatarst


### create new recipe
POST http://localhost:8080/api/recipe
Content-Type: application/json

{
  "name": "test tsar",
  "description": "test long text but longer",
  "servings": 2,
  "time": 10,
  "reference": "Random game",
  "difficulty": "MEDIUM",
  "media": "GAME",
  "taste": "SALTY",
  "vegetarian": false,
  "ingredients": [
    {
      "name": "trava zelena",
      "amount": 10,
      "unit": "PIECES"
    },
    {
      "name": "voda",
      "amount": 1000,
      "unit": "ML"
    }
  ]
}

### delete recipe
DELETE http://localhost:8080/api/recipe/cl3c1f1h30000z6ezyrvv9btj
