name: Google App Engine Deploy
on:
    pull_request:
        branches: [master]
    push:
        branches: [master]

jobs:
    job_id:
        steps:
            - id: 'auth'
              uses: 'google-github-actions/auth@v0'
              with:
                  credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

            - id: 'deploy'
              uses: 'google-github-actions/deploy-appengine@v0'
