name: CI pipline

on:
    pull_request:
        branches: [master]
    push:
        branches: [master]

jobs:
    pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12

            - run: yarn install --frozen-lockfile
            - run: yarn test
